### ISSUE TITLE
When using SCAN XC functional, the ABACUS output exchange energy is 0.

### ISSUE THREAD

**Issue by Liu-RX** [Srlive1201/LibRPA#11]
I tried testing the ABACUS RPA branch from deepmodelling repo with water clusters and SCAN XC functional. The INPUT file content is as follows:
```INPUT_PARAMETERS
#Parameters (General)

calculation scf
ntype   2
dft_functional scan
#nbands   3
#Parameters (Accuracy)
ecutwfc   100

smearing_method  gaussian
basis_type  lcao
#pseudo_type  upf201
ks_solver  genelpa
#dft_functional   hse
exx_separate_loop  1
exx_pca_threshold  1E-3
exx_ccp_rmesh_times 2
exx_c_threshold 1E-4
exx_dm_threshold  1E-3
exx_schwarz_threshold 1E-4
exx_cauchy_threshold 1E-6
rpa   1
```
ABACUS is compiled with libxc to enable the use of SCAN functional. However, the output exchange energy is zero, as follows:
<img width="486" alt="截屏2022-10-06 下午3 48 43" src="https://user-images.githubusercontent.com/75369672/194248494-944029d9-732c-46ac-afef-11c1d4c67014.png">
It seems that the program takes all of exchange correlation energy as correlation energy.

**Comment by minyez** [comment]
I think this should be an issue of ABACUS, instead of LibRPA.

**Comment by xinyangd** [comment]
I have fixed this in ABACUS.
